import js from "@eslint/js";
import globals from "globals";

// One declaration inventory owns classic cross-script dependencies. Unknown
// implicit writes are intentionally absent and remain actionable lint findings.
const legacyDeclarations = {
  "combat.js": {
    combatTimer: "writable",
    combatPanel: "readonly",
    enemyDead: "writable",
    playerDead: "writable",
    hpValidation: "readonly",
    playerAttack: "readonly",
    enemyAttack: "readonly",
    combatBacklog: "readonly",
    addCombatLog: "readonly",
    updateCombatLog: "readonly",
    combatSeconds: "writable",
    startCombat: "readonly",
    endCombat: "readonly",
    combatCounter: "readonly",
    showCombatInfo: "readonly",
  },
  "dungeon.js": {
    dungeonTimer: "writable",
    playTimer: "writable",
    dungeonActivity: "readonly",
    dungeonAction: "readonly",
    dungeonTime: "readonly",
    floorCount: "readonly",
    roomCount: "readonly",
    dungeon: "writable",
    initialDungeonLoad: "readonly",
    dungeonStartPause: "readonly",
    dungeonCounter: "readonly",
    loadDungeonProgress: "readonly",
    dungeonEvent: "readonly",
    engageBattle: "readonly",
    mimicBattle: "readonly",
    guardianBattle: "readonly",
    specialBossBattle: "readonly",
    fleeBattle: "readonly",
    chestEvent: "readonly",
    goldDrop: "readonly",
    nothingEvent: "readonly",
    statBlessing: "readonly",
    cursedTotem: "readonly",
    ignoreEvent: "readonly",
    incrementRoom: "readonly",
    blessingUp: "readonly",
    blessingValidation: "readonly",
    updateDungeonLog: "readonly",
    addDungeonLog: "readonly",
    evaluateDungeon: "readonly",
  },
  "elements.js": {
    playerNameElement: "readonly",
    playerLvlElement: "readonly",
    playerHpElement: "readonly",
    playerCombatHpElement: "readonly",
    playerAtkElement: "readonly",
    playerDefElement: "readonly",
    playerAtkSpdElement: "readonly",
    playerVampElement: "readonly",
    playerCrateElement: "readonly",
    playerCdmgElement: "readonly",
    defaultModalElement: "readonly",
    confirmationModalElement: "readonly",
    sellAllElement: "readonly",
    sellRarityElement: "readonly",
    menuModalElement: "readonly",
  },
  "enemy.js": {
    enemy: "writable",
    generateRandomEnemy: "readonly",
    setEnemyStats: "readonly",
    setEnemyImg: "readonly",
    enemyLoadStats: "readonly",
  },
  "equipment.js": {
    createEquipment: "readonly",
    equipmentIcon: "readonly",
    showItemInfo: "readonly",
    showInventory: "readonly",
    showEquipment: "readonly",
    applyEquipmentStats: "readonly",
    unequipAll: "readonly",
    sellAll: "readonly",
    createEquipmentPrint: "readonly",
  },
  "main.js": {
    runGameplay: "readonly",
    gameServices: "readonly",
    initializeGame: "readonly",
    runLoad: "readonly",
    enterDungeon: "readonly",
    saveData: "readonly",
    calculateStats: "readonly",
    progressReset: "readonly",
    exportData: "readonly",
    importData: "readonly",
    allocationPopup: "readonly",
    objectValidation: "readonly",
  },
  "music.js": {
    sfxCombatEnd: "writable",
    volume: "writable",
    bgmDungeon: "writable",
    bgmBattleMain: "writable",
    bgmBattleBoss: "writable",
    bgmBattleGuardian: "writable",
    sfxEncounter: "writable",
    sfxEnemyDeath: "writable",
    sfxAttack: "writable",
    sfxLvlUp: "writable",
    sfxConfirm: "writable",
    sfxDecline: "writable",
    sfxDeny: "writable",
    sfxEquip: "writable",
    sfxUnequip: "writable",
    sfxOpen: "writable",
    sfxPause: "writable",
    sfxUnpause: "writable",
    sfxSell: "writable",
    sfxItem: "writable",
    sfxBuff: "writable",
    setVolume: "readonly",
  },
  "player.js": {
    player: "writable",
    inventoryOpen: "writable",
    leveled: "writable",
    lvlupSelect: "readonly",
    lvlupPanel: "readonly",
    playerExpGain: "readonly",
    playerLvlUp: "readonly",
    playerLoadStats: "readonly",
    openInventory: "readonly",
    closeInventory: "readonly",
    continueExploring: "readonly",
    lvlupPopup: "readonly",
    generateLvlStats: "readonly",
  },
  "utility.js": {
    nFormatter: "readonly",
    randomizeNum: "readonly",
    randomizeDecimal: "readonly",
  },
};
const legacyBindings = {
  ...Object.assign({}, ...Object.values(legacyDeclarations)),
  Howl: "readonly",
  Howler: "readonly",
};

export default [
  {
    files: ["tests/fixtures/harness/*.js"],
    languageOptions: {
      sourceType: "script",
      globals: { document: "readonly", setInterval: "readonly" },
    },
  },
  {
    ignores: [
      "node_modules/**",
      "dist/**",
      "build/**",
      "coverage/**",
      "playwright-report/**",
      "test-results/**",
      "ci-reports/**",
      ".cache/**",
      ".agents/**",
      ".specify/**",
      ".codex/**",
      "**/*.min.js",
      "art/cosmic-horror/masters/**",
      "art/cosmic-horror/review/baseline/**",
      "tests/fixtures/legacy/source/**",
      "validation/cosmic-horror/reports/**",
      "validation/cosmic-horror/performance/**",
    ],
  },
  {
    ...js.configs.recommended,
    files: ["**/*.js", "**/*.mjs"],
    rules: {
      ...js.configs.recommended.rules,
      eqeqeq: ["error", "always"],
      "no-implicit-globals": "error",
      "prefer-const": "error",
    },
  },
  {
    files: ["assets/js/*.js"],
    languageOptions: {
      sourceType: "script",
      globals: { ...globals.browser, ...legacyBindings },
    },
    rules: {
      // Classic lexical declarations are intentionally consumed by other tags.
      // Local unused variables and arguments remain checked; modules use all.
      "no-unused-vars": ["error", { vars: "local", args: "after-used" }],
    },
  },
  ...Object.entries(legacyDeclarations).map(
    // Ownership is local in the declaring file and ambient only in its consumers.
    ([file, declarations]) => ({
      files: [`assets/js/${file}`],
      languageOptions: {
        globals: Object.fromEntries(
          Object.keys(declarations).map(
            // Turning off an ambient entry lets normal declaration checks apply.
            (name) => [name, "off"],
          ),
        ),
      },
    }),
  ),
  {
    files: ["assets/js/**/*.mjs"],
    languageOptions: { sourceType: "module", globals: globals.browser },
  },
  {
    files: ["*.mjs", "scripts/**/*.mjs", "tests/**/*.mjs"],
    languageOptions: { sourceType: "module", globals: globals.node },
  },
];
